; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]

; `1`  Uncomment one of the following lines to set the default environment
; default_envs = T-Dongle-S3
; default_envs = T-Dongle-S3-Dual
default_envs = T-Dongle-S3-Plus


; `2` Set the source directory to one of the example folders below

; Applicable variants: T-Dongle-S3 or T-Dongle-S3-Plus
src_dir = examples/factory_screen

; Applicable variants: T-Dongle-S3-Dual
; src_dir = examples/factory_no_screen

; Applicable variants: only T-Dongle-S3-Plus
; src_dir = examples/ir_send

; ! Microphone example please use the Arduino IDE and upgrade the ESP32 core to version 3.3.0 or higher.
; src_dir = examples/microphone

; Applicable variants: T-Dongle-S3 or T-Dongle-S3-Plus or  T-Dongle-S3-Dual
; src_dir = examples/sd_card
; src_dir = examples/led
; src_dir = examples/fs_webserver
; src_dir = examples/wireless_sd_storage

; ! USB example please use the Arduino IDE and upgrade the ESP32 core to version 3.3.0 or higher.
; src_dir = examples/usb_hid_mouse
; src_dir = examples/usb_hid_keyboard
; src_dir = examples/usb_mass_storage
; src_dir = examples/usb_mass_storage_led

[env:T-Dongle-S3]
platform = espressif32@6.12.0
framework = arduino
board = dongles3

build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
    -DWIFI_SSID=\"${sysenv.WIFI_SSID}\"
    -DWIFI_PASSWORD=\"${sysenv.WIFI_PASSWORD}\"
    -DWIFI_SSID2=\"${sysenv.WIFI_SSID2}\"
    -DWIFI_PASSWORD2=\"${sysenv.WIFI_PASSWORD2}\"

extra_scripts = post:D:\esp_extra_script\script\combine.py

[env:T-Dongle-S3-Dual]
platform = espressif32@6.12.0
framework = arduino
board = dongles3-dual

[env:T-Dongle-S3-Plus]
platform = espressif32@6.12.0
framework = arduino
board = dongles3-plus
monitor_filters =
	default
	esp32_exception_decoder
    time
build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DWIFI_SSID=\"${sysenv.WIFI_SSID}\"
    -DWIFI_PASSWORD=\"${sysenv.WIFI_PASSWORD}\"
    -DWIFI_SSID2=\"${sysenv.WIFI_SSID2}\"
    -DWIFI_PASSWORD2=\"${sysenv.WIFI_PASSWORD2}\"

extra_scripts = post:D:\esp_extra_script\script\combine.py
